name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
      with:
          version: 10
    - name: pnpm install
      run: pnpm install
    - name: cargo tauri build
      run: cargo tauri build

