name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install tauri-cli
      run: cargo install tauri-cli
    - name: Setup pnpm
      uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
      with:
          version: 10
    - name: pnpm install
      run: pnpm install
    - name: Install prerequisites
      run: sudo apt install libglib2.0-dev libgtk-3-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libasound2-dev
    - name: cargo tauri build
      run: cargo tauri build

